/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test public void testForBitmapTransform() {
        App classUnderTest = new App();
        //some test logic
        // assertion
    }
}
