/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {

        // create instance of bitmap
        if (args.length > 0) {
            String file = args[0];
            BitMap bitMapImage = new BitMap("app/src/main/resources/baldy-8bit.bmp", "app/src/main/resources/newBaldy.bmp");

            // transform image

            if (args[2].equals("grayscale")) {
                bitMapImage.transformGrayScale();
            }

            // write
            bitMapImage.write(args[1]);
        }
    }
}
